apiVersion : apps/v1
kind: Deployment
metadata:
  name: "azureapp"
spec:
  progressDeadlineSeconds: 120
  strategy:
    type: canary
  #replicas: 1
  selector:
    matchLabels:
      app: "azureapp"
  template:
    metadata:
      labels:
        app: "azureapp"
    spec:
      containers:
        - name: "azureapp"
          image: "myakr.azurecr.io/azurerepository:tag1"
          ports:
          - containerPort: 80
