#apiVersion : apps/v1
#kind: Deployment
#metadata:
#  name: azureapp
#spec:
#  progressDeadlineSeconds: 300
#  strategy:
#    type: Recreate
  #replicas: 1
#  selector:
#    matchLabels:
#      app: "azureapp"
#  template:
#    metadata:
#      labels:
#        app: "azureapp"
#    spec:
#      containers:
#        - name: "azureapp"
#          image: "myakr.azurecr.io/azurerepository:tag1"
#          ports:
#          - containerPort: 80
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurerepository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurerepository
  template:
    metadata:
      labels:
        app: azurerepository
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: azurerepository
        image: azurerepository
        ports:
        - containerPort: 80 
          name: azurerepository
---
apiVersion: v1
kind: Service
metadata:
  name: azurerepository
spec:
  ports:
  - port: 80
  selector:
    app: azurerepository
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurerepository
spec:
  replicas: 1
  selector:
    matchLabels:
      app: azurerepository
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: azurerepository
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": windows
      containers:
      - name: azurerepository
        image: myakr.azurecr.io/azurerepository:tag1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
        #env:
        #- name: REDIS
        #  value: "azure-vote-back"
---
apiVersion: v1
kind: Service
metadata:
  name: azurerepository
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: azurerepository
