apiVersion: v1
kind: Service
metadata:
    name: hello-azurerepository
    labels:
        app: hello-azurerepository
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: hello-azurerepository
